### PR TITLE
New protocols: Good classes extractor and Volume extractor

### PR DESCRIPTION
**Pull request by danielmarchan3**
Set of protocols that will be helpful for reaching 3D processing:
- Extracts particles from the selected 2D classes (streaming)
- Extracts the volume and particles from a 3D class

### CODE REVIEW

**Review by albertmena — CHANGES_REQUESTED** [review]
both test fails with the same error:
 ERROR:'NoneType' object has no attribute 'getName'

**Comment by albertmena** [comment]
Why is this protocol in facilities and not in scipion-em-xmipp?

**Comment by danielmarchan3** [comment]
> both test fails with the same error: ERROR:'NoneType' object has no attribute 'getName'

I tried again updating all the repos and I cannot reproduce that error. This error was given by simply running the tests?

**Comment by albertmena** [comment]
> > Why is this protocol in facilities and not in scipion-em-xmipp?
> 
> These two protocols have no processing steps, nor do they call any XMIPP programs. Initially, we planned to upload them to scipion-em. However, considering that these two protocols are highly specific for on-the-fly workflows, we concluded that this repo would be the most suitable place to submit them.

Perfect, thanks

**Review by albertmena — APPROVED** [review]

**Pull request merged**
